apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdocker
  labels:
    app: springdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springdocker
  template:
    metadata:
      labels:
        app: springdocker
    spec:
      containers:
      - name: springdocker
        image: sampath2014/springdocker
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springdocker-service
spec:
  selector:
    app: springdocker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080